### ISSUE TITLE
Parser do not recognize Lab and Proj classes

### ISSUE THREAD

**Issue by mmelaniuk** [MaciejLisCK/WatCalendarToGoogleCalendar#1]
I have 2 subjects:
Diagnostyka i wiarygodność SK (p)
Diagnostyka i wiarygodność SK (L)
and both are parsed to: DIWS which is wrong:-(
It should be:
DIWSK (p)
DIWSK (L)
so I know if I should be prepared on the classes or maybe I can just come and sit watching sweet kittens on YouTube:-)

**Comment by MaciejLisCK** [comment]
Parser is fine, the subjects are wrong 👍 



![kitten-6](https://cloud.githubusercontent.com/assets/1531086/23401585/8cf765a0-fda8-11e6-98d9-02098bcddaf5.jpg)

**Comment by mmelaniuk** [comment]
No it is not fine, now I have all classes the same and I will go unprepared just to watch youtube and propably I will lose my job because of it incompatibility. 
Please fix this bug ASAP.

This bug's importance level is now: Critical.

**Comment by MaciejLisCK** [comment]
It's not a bug, it's a feature.
